const KEY='ninku-v1';
const defaults={entries:[],sites:['現場A'],workers:['作業者A'],processes:['一般作業','組立','解体'],targets:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(JSON.stringify(defaults));data.targets=data.targets||[];
const $=id=>document.getElementById(id),save=()=>localStorage.setItem(KEY,JSON.stringify(data)),today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const key=(site,process)=>site+'|||'+process,fmt=n=>Number(n).toFixed(2).replace(/\.00$/,'');
function fill(id,values){$(id).innerHTML='<option value="">選択してください</option>'+values.map(v=>`<option>${esc(v)}</option>`).join('')}
function getTarget(site,process){return data.targets.find(t=>t.site===site&&t.process===process)}
function ninku(e){return Number(e.ninku??(Number(e.people)*Number(e.hours)/7))}
function used(site,process,ignore=''){return data.entries.filter(e=>e.site===site&&e.process===process&&e.id!==ignore).reduce((s,e)=>s+ninku(e),0)}
function render(){['sites','workers','processes'].forEach(k=>{$(k+'List').innerHTML=data[k].map((v,i)=>`<li>${esc(v)}<button class="remove" data-remove="${k}" data-index="${i}">×</button></li>`).join('')});fill('site',data.sites);fill('targetSite',data.sites);fill('worker',data.workers);fill('process',data.processes);fill('targetProcess',data.processes);renderTargets();renderRecent();renderSummary();save()}
function renderTargets(){$('targetsList').innerHTML=data.targets.map((t,i)=>`<li><span><b>${esc(t.site)}</b> / ${esc(t.process)}　目標 <b>${fmt(t.ninku)}人工</b></span><button class="remove" data-target-remove="${i}">×</button></li>`).join('')}
function renderRecent(){const a=[...data.entries].sort((x,y)=>y.date.localeCompare(x.date));$('recentEntries').innerHTML='<h3 class="recent-title">最近の記録</h3>'+(a.length?a.slice(0,5).map(e=>`<div class="recent-item"><div><strong>${esc(e.site)}　${esc(e.process)}</strong><small>${e.date}　${esc(e.worker)}　使用 ${fmt(ninku(e))}人工</small></div><span class="badge">${fmt(ninku(e))}人工</span></div>`).join(''):'<div class="card empty">記録を保存すると、ここに表示されます。</div>')}
function renderSummary(){const a=[...data.entries].sort((x,y)=>y.date.localeCompare(x.date));$('totalCount').textContent=a.length;$('totalManDays').textContent=fmt(a.reduce((s,e)=>s+ninku(e),0));$('totalHours').textContent=fmt(a.reduce((s,e)=>s+Number(e.people)*Number(e.hours),0));$('summaryPeriod').textContent=a.length?`${a[a.length-1].date} ～ ${a[0].date}`:'記録を追加すると集計されます';const map={};data.entries.forEach(e=>{const k=key(e.site,e.process);map[k]??={site:e.site,process:e.process,used:0};map[k].used+=ninku(e)});data.targets.forEach(t=>{const k=key(t.site,t.process);map[k]??={site:t.site,process:t.process,used:0}});const rows=Object.values(map);$('emptyUsage').classList.toggle('hidden',!!rows.length);$('usageTable').innerHTML=rows.map(x=>{const t=getTarget(x.site,x.process),remain=t?Number(t.ninku)-x.used:null,over=t&&remain<0;return `<tr class="${over?'over':''}"><td>${esc(x.site)}</td><td>${esc(x.process)}</td><td>${t?fmt(t.ninku):'未設定'}</td><td>${fmt(x.used)}</td><td>${t?fmt(remain):'—'}</td><td>${over?'<b class="warning">⚠ 目標超過</b>':t?'OK':'目標未設定'}</td></tr>`}).join('');$('summaryAlerts').innerHTML=rows.filter(x=>{const t=getTarget(x.site,x.process);return t&&x.used>Number(t.ninku)}).map(x=>`<div class="alert">⚠ ${esc(x.site)} / ${esc(x.process)} の使用人工が目標を超えています。</div>`).join('');$('entriesTable').innerHTML=a.map(e=>`<tr><td>${e.date}</td><td><b>${esc(e.site)}</b><br><span class="muted">${esc(e.process)}</span></td><td>${esc(e.worker)}</td><td>${fmt(ninku(e))}人工</td><td><button class="action" data-edit="${e.id}">編集</button><button class="action delete" data-delete="${e.id}">削除</button></td></tr>`).join('')}
function reset(){ $('workForm').reset();$('date').value=today();$('people').value=1;$('hours').value=7;$('ninku').value='';$('editId').value='';$('cancelEdit').hidden=true;$('entryWarning').innerHTML=''}
$('date').value=today();$('workForm').addEventListener('submit',e=>{e.preventDefault();const id=$('editId').value||crypto.randomUUID(),item={id,date:$('date').value,site:$('site').value,worker:$('worker').value,process:$('process').value,people:$('people').value,hours:$('hours').value,ninku:$('ninku').value===''?Number($('people').value)*Number($('hours').value)/7:Number($('ninku').value),note:$('note').value};if(!item.site||!item.worker||!item.process)return alert('現場・作業者・作業を選択してください。');const t=getTarget(item.site,item.process),total=used(item.site,item.process,id)+item.ninku;$('entryWarning').innerHTML=t&&total>Number(t.ninku)?`<div class="alert">⚠ ${item.site} / ${item.process} の合計 ${fmt(total)}人工が目標 ${fmt(t.ninku)}人工を超えます。</div>`:'';const i=data.entries.findIndex(x=>x.id===id);i>=0?data.entries[i]=item:data.entries.push(item);save();reset();render();alert('保存しました。')});
$('saveTarget').onclick=()=>{const site=$('targetSite').value,process=$('targetProcess').value,n=Number($('targetNinku').value);if(!site||!process||!Number.isFinite(n)||n<0)return alert('現場・作業・目標人工を入力してください。');const t=getTarget(site,process);if(t)t.ninku=n;else data.targets.push({site,process,ninku:n});$('targetNinku').value='';render()};
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(tab.dataset.tab).classList.add('active')}const add=e.target.closest('[data-add]');if(add){const input=add.previousElementSibling,v=input.value.trim();if(v&&!data[add.dataset.add].includes(v)){data[add.dataset.add].push(v);input.value='';render()}}const rem=e.target.closest('[data-remove]');if(rem){data[rem.dataset.remove].splice(Number(rem.dataset.index),1);render()}const tr=e.target.closest('[data-target-remove]');if(tr){data.targets.splice(Number(tr.dataset.targetRemove),1);render()}const del=e.target.closest('[data-delete]');if(del&&confirm('この記録を削除しますか？')){data.entries=data.entries.filter(x=>x.id!==del.dataset.delete);render()}const edit=e.target.closest('[data-edit]');if(edit){const x=data.entries.find(v=>v.id===edit.dataset.edit);$('editId').value=x.id;$('date').value=x.date;$('site').value=x.site;$('worker').value=x.worker;$('process').value=x.process;$('people').value=x.people;$('hours').value=x.hours;$('ninku').value=x.ninku;$('note').value=x.note||'';$('cancelEdit').hidden=false;document.querySelector('[data-tab="entry"]').click();scrollTo(0,0)}});
$('cancelEdit').onclick=reset;$('clearData').onclick=()=>{if(confirm('すべてのデータを削除しますか？')){localStorage.removeItem(KEY);data=JSON.parse(JSON.stringify(defaults));render()}};$('exportCsv').onclick=()=>{if(!data.entries.length)return alert('出力する記録がありません。');const rows=[['日付','現場','作業者','作業','人数','作業時間','使用人工','備考'],...data.entries.map(e=>[e.date,e.site,e.worker,e.process,e.people,e.hours,fmt(ninku(e)),e.note||''])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`作業日報_${today()}.csv`;a.click()};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
