const KEY='ninku-v1';
const defaults={entries:[],sites:['現場A'],workers:['作業者A'],processes:['一般作業','組立','解体']};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const today=()=>new Date().toISOString().slice(0,10);
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function fillSelect(id,values){$(id).innerHTML='<option value="">選択してください</option>'+values.map(v=>`<option>${escape(v)}</option>`).join('');}
function render(){['sites','workers','processes'].forEach(k=>{const label={sites:'現場',workers:'作業者',processes:'工程'}[k];$(k+'List').innerHTML=data[k].map((v,i)=>`<li>${escape(v)}<button class="remove" data-remove="${k}" data-index="${i}" aria-label="${label}を削除">×</button></li>`).join('')});fillSelect('site',data.sites);fillSelect('worker',data.workers);fillSelect('process',data.processes);renderEntries();renderSummary();save();}
function man(e){return (Number(e.people)*Number(e.hours)/7).toFixed(2).replace(/\.00$/,'');}
function renderEntries(){const sorted=[...data.entries].sort((a,b)=>b.date.localeCompare(a.date));$('recentEntries').innerHTML='<h3 class="recent-title">最近の記録</h3>'+ (sorted.length?sorted.slice(0,5).map(e=>`<div class="recent-item"><div><strong>${escape(e.site)}　${escape(e.process)}</strong><small>${escape(e.date)}　${escape(e.worker)}　${e.people}人・${e.hours}時間</small></div><span class="badge">${man(e)}人工</span></div>`).join(''):'<div class="card empty">記録を保存すると、ここに表示されます。</div>');}
function renderSummary(){const es=[...data.entries].sort((a,b)=>b.date.localeCompare(a.date));$('totalCount').textContent=es.length;$('totalHours').textContent=es.reduce((s,e)=>s+Number(e.people)*Number(e.hours),0).toFixed(2).replace(/\.00$/,'');$('totalManDays').textContent=es.reduce((s,e)=>s+Number(man(e)),0).toFixed(2).replace(/\.00$/,'');$('summaryPeriod').textContent=es.length?`${es[es.length-1].date} ～ ${es[0].date}`:'記録を追加すると集計されます';$('emptySummary').classList.toggle('hidden',!!es.length);$('entriesTable').innerHTML=es.map(e=>`<tr><td>${escape(e.date)}</td><td><b>${escape(e.site)}</b><br><span class="muted">${escape(e.process)}</span></td><td>${escape(e.worker)}</td><td>${e.people}人</td><td>${e.hours}h</td><td><b>${man(e)}</b></td><td><button class="action" data-edit="${e.id}">編集</button><button class="action delete" data-delete="${e.id}">削除</button></td></tr>`).join('');}
$('date').value=today();
$('workForm').addEventListener('submit',e=>{e.preventDefault();const item={id:$('editId').value||crypto.randomUUID(),date:$('date').value,site:$('site').value,worker:$('worker').value,process:$('process').value,people:$('people').value,hours:$('hours').value,note:$('note').value};if(!item.site||!item.worker||!item.process)return alert('現場・作業者・工程を選択してください。');const i=data.entries.findIndex(x=>x.id===item.id);i>=0?data.entries[i]=item:data.entries.push(item);save();e.target.reset();$('date').value=today();$('people').value=1;$('hours').value=7;$('editId').value='';$('cancelEdit').hidden=true;render();alert('保存しました。');});
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(tab.dataset.tab).classList.add('active');return}const add=e.target.closest('[data-add]');if(add){const input=add.previousElementSibling,v=input.value.trim();if(v&&!data[add.dataset.add].includes(v)){data[add.dataset.add].push(v);input.value='';render();}}const rem=e.target.closest('[data-remove]');if(rem){data[rem.dataset.remove].splice(Number(rem.dataset.index),1);render()}const del=e.target.closest('[data-delete]');if(del&&confirm('この記録を削除しますか？')){data.entries=data.entries.filter(x=>x.id!==del.dataset.delete);render()}const edit=e.target.closest('[data-edit]');if(edit){const x=data.entries.find(v=>v.id===edit.dataset.edit);if(x){$('editId').value=x.id;$('date').value=x.date;$('site').value=x.site;$('worker').value=x.worker;$('process').value=x.process;$('people').value=x.people;$('hours').value=x.hours;$('note').value=x.note||'';$('cancelEdit').hidden=false;document.querySelector('[data-tab="entry"]').click();scrollTo(0,0)}}});
$('cancelEdit').onclick=()=>{$('workForm').reset();$('date').value=today();$('people').value=1;$('hours').value=7;$('editId').value='';$('cancelEdit').hidden=true};
$('clearData').onclick=()=>{if(confirm('すべてのデータを削除しますか？')){localStorage.removeItem(KEY);data=JSON.parse(JSON.stringify(defaults));render()}};
$('exportCsv').onclick=()=>{if(!data.entries.length)return alert('出力する記録がありません。');const rows=[['日付','現場','作業者','工程','人数','作業時間','人工','備考'],...data.entries.map(e=>[e.date,e.site,e.worker,e.process,e.people,e.hours,man(e),e.note||''])];const csv='\\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\\r\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`作業日報_${today()}.csv`;a.click();URL.revokeObjectURL(a.href)};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
